LIBRARY_NAME = png
png_C_FILES = png.c  pngerror.c  pngget.c  pngmem.c  pngpread.c  pngread.c  pngrio.c  pngrtran.c  pngrutil.c  pngset.c  pngtrans.c  pngwio.c  pngwrite.c  pngwtran.c  pngwutil.c
png_CFLAGS = -DHAVE_CONFIG_H -I. -DPNG_CONFIGURE_LIBPNG
png_LDFLAGS = -lz

include ../framework/makefiles/common.mk
include ../framework/makefiles/library.mk
