ifeq ($(FW_TARGET_LOADED),)
FW_TARGET_LOADED := 1
FW_TARGET_NAME := windows
FW_TARGET_DEFINE := WINDOWS

TARGET_CC ?= i686-mingw32-gcc
TARGET_CXX ?= i686-mingw32-g++
TARGET_STRIP ?= i686-mingw32-strip
TARGET_CODESIGN_ALLOCATE ?=
TARGET_CODESIGN ?= :
TARGET_CODESIGN_FLAGS ?=

SDKFLAGS :=
endif
