LIBRARY_NAME = z
z_C_FILES = adler32.c compress.c crc32.c deflate.c gzclose.c gzlib.c gzread.c gzwrite.c infback.c inffast.c inflate.c inftrees.c trees.c uncompr.c zutil.c

include ../framework/makefiles/common.mk
include ../framework/makefiles/staticlib.mk
